RazorPagesCrud/Models/Domain/Funcionario.cs
namespace RazorPagesCrud.Models.Domain
{
    public class Funcionario
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Email  { get; set; }  

        public long Salary { get; set; }

        public DateTime DateOfBirth { get; set; }

        public string Departament { get; set; }
    }
}

RazorPagesCrud/Models/ViewModels/AddFuncionarioViewModelClass.cs
namespace RazorPagesCrud.Models.ViewModels
{
	public class AddFuncionarioViewModelClass
	{

		public string Name { get; set; }

		public string Email { get; set; }

		public long Salary { get; set; }

		public DateTime DateOfBirth { get; set; }

		public string Departament { get; set; }
	}
}

RazorPagesCrud/Models/ViewModels/EditFuncionarioViewModel.cs
namespace RazorPagesCrud.Models.ViewModels
{
	public class EditFuncionarioViewModel
	{
		public Guid Id { get; set; }

		public string Name { get; set; }

		public string Email { get; set; }

		public long Salary { get; set; }

		public DateTime DateOfBirth { get; set; }

		public string Departament { get; set; }
	}
}

RazorPagesCrud/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPagesCrud.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesCrud/Pages/Funcionarios/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesCrud.Models.ViewModels;
using RazorPagesCrud.Data;
using System.ComponentModel.DataAnnotations;
using RazorPagesCrud.Models.Domain;

namespace RazorPagesCrud.Pages.Funcionarios
{
    public class AddModel : PageModel
    {
        private readonly RazorPagesDbContext dbContext;
		public AddModel(RazorPagesDbContext dbContext) {
        this.dbContext = dbContext;
        }

        [BindProperty]
        public AddFuncionarioViewModelClass AddFuncionarioRequest { get; set;}

        public void OnGet()
        {
        }

        public void OnPost() 
        {
            var funcionarioDomainModel = new Funcionario
            {   
                Name = AddFuncionarioRequest.Name,
                Email = AddFuncionarioRequest.Email,
                Salary = AddFuncionarioRequest.Salary,  
                DateOfBirth = AddFuncionarioRequest.DateOfBirth,
                Departament = AddFuncionarioRequest.Departament
            };

            dbContext.Funcionarios.Add(funcionarioDomainModel);
            dbContext.SaveChanges();
            ViewData["Message"] = "Funcionario cadastrado com sucesso";
        }
    }
}

RazorPagesCrud/Pages/Funcionarios/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesCrud.Data;
using RazorPagesCrud.Models.Domain;
using RazorPagesCrud.Models.ViewModels;

namespace RazorPagesCrud.Pages.Funcionarios
{
    public class EditModel : PageModel
    {
		private readonly RazorPagesDbContext dbContext;

		[BindProperty]
        public EditFuncionarioViewModel EditFuncionarioViewModel { get; set; }
        public EditModel(RazorPagesDbContext dbContext)
		{
			this.dbContext = dbContext;
		}

		public void OnGet(Guid id)
        {
			
			var funcionario = dbContext.Funcionarios.Find(id);

			if(funcionario != null)
			{
				 EditFuncionarioViewModel = new EditFuncionarioViewModel()
				{
					Id = funcionario.Id,
					Name = funcionario.Name,
					Email = funcionario.Email,
					DateOfBirth = funcionario.DateOfBirth,
					Departament = funcionario.Departament,
				};
			}
        }
		public void OnPostUpdate() 
		{
			if (EditFuncionarioViewModel != null )
			{
				var existingFuncionario = dbContext.Funcionarios.Find(EditFuncionarioViewModel.Id);
				if (existingFuncionario != null)
				{

						
						existingFuncionario.Name = EditFuncionarioViewModel.Name;
						existingFuncionario.Email = EditFuncionarioViewModel.Email;
						existingFuncionario.Salary = EditFuncionarioViewModel.Salary;
						existingFuncionario.DateOfBirth = EditFuncionarioViewModel.DateOfBirth;
						existingFuncionario.Departament = EditFuncionarioViewModel.Departament;

					dbContext.SaveChanges();
					ViewData["Message"] = "Funcionario atualizado com sucesso";
				}
			}
			

		} 
		public IActionResult OnPostDelete()
		{
			var existingFuncionario = dbContext.Funcionarios.Find(EditFuncionarioViewModel.Id);
			if (existingFuncionario != null)
			{
				dbContext.Funcionarios.Remove(existingFuncionario); 
				dbContext.SaveChanges();
				return RedirectToPage("/Funcionarios/List");
			}
			return Page();

			

		}
    }
}

RazorPagesCrud/Pages/Funcionarios/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesCrud.Data;

namespace RazorPagesCrud.Pages.Funcionarios
{
    public class ListModel : PageModel
    {
		private readonly RazorPagesDbContext dbContext;

        public List<Models.Domain.Funcionario> Funcionarios { get; set; }

        public ListModel(RazorPagesDbContext dbContext)
		{
			this.dbContext = dbContext;
		}

		public void OnGet()
        {
            Funcionarios = dbContext.Funcionarios.ToList();
        }
    }
}

RazorPagesCrud/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesCrud.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorPagesCrud/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesCrud.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesCrud/Pages/Funcionarios/Add.cshtml
@page
@model RazorPagesCrud.Pages.Funcionarios.AddModel
@{
    var message = ViewData["Message"]?.ToString();
}

<form method="post" class="needs-validation" novalidate>
    
        <h1 class="mb-3">Adicione um novo funcionário</h1>


    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }

    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" asp-for="AddFuncionarioRequest.Name" required>
        <div class="invalid-feedback">Por favor, preencha o campo Nome.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" asp-for="AddFuncionarioRequest.Email" required>
        <div class="invalid-feedback">Por favor, preencha um email válido.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Salario</label>
        <input type="number" class="form-control" asp-for="AddFuncionarioRequest.Salary" required>
        <div class="invalid-feedback">Por favor, preencha o campo Salario.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Data de Nascimento</label>
        <input type="date" class="form-control" asp-for="AddFuncionarioRequest.DateOfBirth" required>
        <div class="invalid-feedback">Por favor, preencha a Data de Nascimento.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Departamento</label>
        <input type="text" class="form-control" asp-for="AddFuncionarioRequest.Departament" required>
        <div class="invalid-feedback">Por favor, preencha o campo Departamento.</div>
    </div>

    <div class="d-flex justify-content-between align-items-center mb-3">
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a href="/Funcionarios/list" class="btn btn-secondary">Voltar</a>
    </div>
</form>

<script>
    // Validação do lado do cliente usando JavaScript
    (function () {
        'use strict';
        // Obtém todos os formulários que precisam de validação
        var forms = document.querySelectorAll('.needs-validation');

        // Loop através dos formulários e previne o envio vazio
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                form.classList.add('was-validated');
            }, false);
        });
    })();
</script>

RazorPagesCrud/Pages/Funcionarios/Edit.cshtml
@page "{id:Guid}"
@model RazorPagesCrud.Pages.Funcionarios.EditModel
@{
    var message = ViewData["message"]?.ToString();
}

<form method="post" class="needs-validation" novalidate>
    <h1 class="mb-3">Editar funcionário</h1>

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }

    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="EditFuncionarioViewModel.Id" readonly>
    </div>

    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input type="text" class="form-control" asp-for="EditFuncionarioViewModel.Name" required>
        <div class="invalid-feedback">Por favor, preencha o campo Nome.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" asp-for="EditFuncionarioViewModel.Email" required>
        <div class="invalid-feedback">Por favor, preencha um email válido.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Salário</label>
        <input type="number" class="form-control" asp-for="EditFuncionarioViewModel.Salary" required>
        <div class="invalid-feedback">Por favor, preencha o campo Salário.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Data de Nascimento</label>
        <input type="date" class="form-control" asp-for="EditFuncionarioViewModel.DateOfBirth" required>
        <div class="invalid-feedback">Por favor, preencha a Data de Nascimento.</div>
    </div>

    <div class="mb-3">
        <label class="form-label">Departamento</label>
        <input type="text" class="form-control" asp-for="EditFuncionarioViewModel.Departament" required>
        <div class="invalid-feedback">Por favor, preencha o campo Departamento.</div>
    </div>

    <div class="mb-3 d-flex justify-content-between">
        <button type="submit" class="btn btn-primary" asp-page-handler="Update">Atualizar</button>
        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
        <button type="button" class="btn btn-secondary" onclick="location.href='/Funcionarios/list'">Voltar</button>

    </div>
</form>

<script>
    // Validação do lado do cliente usando JavaScript
    (function () {
        'use strict';
        // Obtém todos os formulários que precisam de validação
        var forms = document.querySelectorAll('.needs-validation');

        // Loop através dos formulários e previne o envio vazio
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                form.classList.add('was-validated');
            }, false);
        });
    })();
</script>

RazorPagesCrud/Pages/Funcionarios/List.cshtml
@page
@model RazorPagesCrud.Pages.Funcionarios.ListModel
@{
}

<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="mb-3">Lista de Funcionários</h1>
<a href="/Funcionarios/add" class="btn btn-primary">Cadastrar Funcionário</a>
</div>
@if(Model.Funcionarios != null && Model.Funcionarios.Any())
	{
		<table class="table">
			<thead>
				<tr>
					<th>Id </th>
					<th>Name </th>
					<th>Email </th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			@foreach (var funcionario in Model.Funcionarios )
			{
					<tr>
						<td>@funcionario.Id</td>
						<td>@funcionario.Name</td>
						<td>@funcionario.Email</td>
						<th>
							<a href="/Funcionarios/Edit/@funcionario.Id" class="btn btn-dark">Edit</a>
						</th>
					</tr>
			}
			</tbody> 
		</table>

	}
	else{
		<p>Não há funcionários</p>
	}

RazorPagesCrud/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a href="/Funcionarios/list" class="btn btn-primary">Ir para lista de Funcionários</a>
</div>

RazorPagesCrud/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorPagesCrud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPagesCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RazorPagesCrud - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>